services:
  bootstrap:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - workspace:/app/workspace
    working_dir: /app/workspace
    platform: linux/amd64
    tty: true
    user: bootstrap
    init: true
    entrypoint: ["/bin/sh", "-c", "cp -r /app/deployments/nested_vsphere /app/workspace/ && /bin/bash"]

volumes:
  workspace:
