
- name: Wait for Avi
  ansible.builtin.uri:
    url: https://{{ avi_management_ip }}
    validate_certs: false
    timeout: 10
    method: GET
    body_format: json
    return_content: true
    status_code: 200
  register: result
  until: result is succeeded
  retries: 10
  delay: 60

- name: Default password
  vmware.alb.avi_useraccount:
    avi_credentials:
      username: "admin"
      password: "{{ avi_default_password }}"
      controller: "{{ avi_management_ip }}"
    old_password: "{{ avi_default_password }}"
    password: "{{ avi_password }}"
    force_change: false
  ignore_errors: true

- name: System configuration
  vmware.alb.avi_systemconfiguration:
    avi_credentials:
      username: "admin"
      password: "{{ avi_password }}"
      controller: "{{ avi_management_ip }}"
    state: present
    welcome_workflow_complete: true
    default_license_tier: ENTERPRISE
    portal_configuration:
      allow_basic_authentication: true
    dns_configuration:
      search_domain: "{{ domain_name }}"
      server_list:
        - type: V4
          addr: "{{ dns_server }}"
    ntp_configuration:
      ntp_servers:
        - server:
            type: >-
              {%- if ntp_server | ansible.utils.ipv4 -%} V4
              {%- else -%}                               DNS
              {%- endif -%}
            addr: "{{ ntp_server }}"

- name: Backup configuration
  vmware.alb.avi_backupconfiguration:
    avi_credentials:
      username: "admin"
      password: "{{ avi_password }}"
      controller: "{{ avi_management_ip }}"
    state: present
    name: Backup-Configuration
    backup_passphrase: "{{ avi_password }}"
    backup_file_prefix: "avi-"
    save_local: true

