---
- name: Download ISO locally for {{ deployment_v2_router_runtime_iso_source }}
  ansible.builtin.get_url:
    url: "{{ deployment_v2_router_runtime_iso_source_map[deployment_v2_router_runtime_iso_source].url }}"
    dest: >-
      {{ deployment_v2_router_runtime_install_source_root }}/{{ deployment_v2_router_runtime_iso_source }}/{{
      deployment_v2_router_runtime_iso_local_filename }}
    mode: "0644"
    force: true
    timeout: 1800

- name: Mount ISO from local file for {{ deployment_v2_router_runtime_iso_source }}
  ansible.builtin.command:
    argv:
      - /usr/bin/timeout
      - "60"
      - /usr/bin/mount
      - -t
      - iso9660
      - -o
      - loop,ro
      - >-
        {{ deployment_v2_router_runtime_install_source_root }}/{{ deployment_v2_router_runtime_iso_source }}/{{
        deployment_v2_router_runtime_iso_local_filename }}
      - "{{ deployment_v2_router_runtime_install_source_root }}/{{ deployment_v2_router_runtime_iso_source }}/mounted"
  changed_when: true
