- name: Deploy NSX Manager OVA
  vmware.ansible_for_nsxt.nsxt_deploy_ova:
    ovftool_path: "{{ ovftool_path }}"
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    portgroup: "{{ management_portgroup_name }}"
    cluster: "{{ cluster_name }}"
    vmname: "{{ nsx_node1.vmname }}"
    hostname: "{{ nsx_node1.hostname }}"
    dns_server: "{{ dns_server }}"
    dns_domain: "{{ domain }}"
    ntp_server: "{{ ntp_server }}"
    gateway: "{{ gateway }}"
    ip_address: "{{ nsx_node1.ip }}"
    netmask: "{{ netmask }}"
    admin_password: "{{ nsx_password }}"
    cli_password: "{{ nsx_password }}"
    path_to_ova: "{{ nsx_ova_path }}"
    ova_file: "{{ nsx_ova }}"
    vcenter: "{{ vc_address }}"
    vcenter_user: "{{ vc_username }}"
    vcenter_passwd: "{{ vc_password }}"
    deployment_size: "{{ nsx_manager_deployment_size }}"
    role: "NSX Manager"

- name: Check manager status
  vmware.ansible_for_nsxt.nsxt_manager_status:
    hostname: "{{ nsx_node1.ip }}"
    username: "{{ nsx_username }}"
    password: "{{ nsx_password }}"
    validate_certs: "{{ validate_certs }}"
    wait_time: 50
