---
- name: Deploy Avi controller ova
  gather_facts: false
  hosts: all
  vars:
    validate_certs: false
    nsx_state: "present"
  tasks:
    - name: Setup variables for NSX Advanced Load Balancer
      ansible.builtin.set_fact:
        validate_certs: false
        vc_address: '{{ vc_address }}'
        vc_username: '{{ vc_username }}'
        vc_password: '{{ vc_password }}'

        domain: '{{ domain_name }}'
        netmask: '{{ netmask }}'
        gateway: '{{ gateway }}'

        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
        datastore_name: '{{ datastore_name }}'
        management_portgroup_name: '{{ management_portgroup_name }}'

        ovftool_path: '{{ ovftool_path }}'

        avi_ova_path: '{{ avi_ova_path }}'
        avi_vm_name: '{{avi_vm_name}}'
        avi_hostname: '{{ avi_hostname }}'
        avi_management_ip: '{{ avi_management_ip }}'

        vcenter_host: '{{ vc_address }}'
        vcenter_user: '{{ vc_username }}'
        vcenter_password: '{{ vc_password }}'
        con_datacenter: '{{ datacenter_name }}'
        con_cluster: '{{ cluster_name }}'
        con_mgmt_network: '{{ management_portgroup_name }}'
        con_ova_path: '{{ avi_ova_path }}'
        con_vm_name: '{{ avi_vm_name }}'
        con_disk_mode: thin
        con_datastore: '{{ datastore_name }}'
        con_mgmt_ip: '{{ avi_management_ip }}'
        con_mgmt_mask: '{{ netmask }}'
        con_default_gw: '{{ gateway }}'
        con_power_on: true

    - name: Deploy Avi
      ansible.builtin.import_role:
        name: avi_000_deploy
