---
- name: Deploy VPC Connectivity Profile
  hosts: all
  gather_facts: false
  tasks:
    - name: Setup variables for VPC Connectivity Profile
      ansible.builtin.set_fact:
        nsx_manager_hostname: '{{ nsx_hostname }}'
        nsx_manager_username: '{{ nsx_username }}'
        nsx_manager_password: '{{ nsx_password }}'

        # VPC Spec
        edge_cluster_name: "{{ edge_cluster_name }}"
        tier0_gateway_name: "{{ t0_name }}"
        t0_locale_service_name: "{{ t0_locale_service_name }}"

        # IP Blocks
        external_ip_block_cidr: "{{ external_ip_block_cidr }}"
        private_ip_block_cidr: "{{ private_ip_block_cidr }}"

    - name: Deploy VPC Connectivity Profile
      ansible.builtin.include_role:
        name: nsx_create_vpc_connectivity_profile
